### ISSUE TITLE
Package stasis for CPAN

### ISSUE THREAD

**Issue by dnmfarrell** [dnmfarrell/Stasis#1]
Will need to create a Makefile.PL etc

**Comment by jonasbn** [comment]
Do you have any build-system preferences?
- [Dist::Zilla](https://metacpan.org/pod/Dist::Zilla)
- [ExtUtils::MakeMaker](https://metacpan.org/pod/ExtUtils::MakeMaker)
- [Module::Build](https://metacpan.org/pod/Module::Build)
- [Module::Install](https://metacpan.org/pod/distribution/Module-Install/lib/Module/Install.pod)

ExtUtils::MakeMaker is the old defacto standard, the others are more modern takes on the same thing and Dist::Zilla is like top-of-the-line, with plugins and everything, but with a whole lot of dependencies for the developer, but it produces a nice Makefile.PL

There are other alternatives on CPAN aswell.

jonasbn

**Comment by dnmfarrell** [comment]
Hey thanks, I edited your commit msg to close this issue. A basic Makefile.PL was exactly what I wanted, thanks again.
